docs(README): 更新 README-zh.md 和 README.md
- 修订和合并了 README-zh.md 的内容，结合了 npx 和独立可执行文件的使用示例
- 更新了 README.md 的格式，使徽标链接可点击
- 添加了 CI 工作流中的 Commit and Push 步骤，以自动更新 README-zh.md

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,6 +63,16 @@ jobs:
         run: |
           pnpm test || (echo "Test failed" && exit 1)
 
+      - name: Commit and Push
+        run: |
+          git add README-zh.md
+          git config --local user.email "action@h7ml.cn"
+          git config --local user.name "GitHub Action"
+          git config advice.ignoredHook false
+          git commit -m "docs(README): update README-zh.md"
+          BRANCH=$(echo "${GITHUB_REF}" | sed 's@refs/heads/@@')
+          git push origin HEAD:$BRANCH || echo "Push to repository failed"
+
       - name: Upload build artifacts
         uses: actions/upload-artifact@v3
         with:
